### PR TITLE
add Eval() to execute code in the current vm scope

### PR DESCRIPTION
**Pull request by deoxxa**

### CODE REVIEW

**Comment by darkliquid** [comment]
would like to see a test to demonstrate it, but looks good :+1:

**Comment by deoxxa** [comment]
Yep, definitely will be putting together some tests!

**Comment by deoxxa** [comment]
@darkliquid does that set of tests illustrate its use well enough?

**Comment by darkliquid** [comment]
Looks good. Took me a little while to figure out what it was doing (which might mean a few comments are in order), but once it clicked it was pretty clear.

:+1:

**Comment by deoxxa** [comment]
There are some comments there now - do they do a good enough job of explaining what's going on?

**Comment by darkliquid** [comment]
Perfect. Nice job!

**Comment by deoxxa** [comment]
Awesome - thanks for keeping an eye on it for me!

**Pull request merged**
