### PR TITLE
Fix a panic in value export when an array has multiple types of arrays

### LINKED ISSUE #279: panic - Mixed type array gives panic on export
```Go
package main

import (
	"fmt"
	"github.com/robertkrimen/otto"
)

func main() {

	vm := otto.New()

	_, err := vm.Run(`
var output = [[1,2.1], [3, 4]];
	`)

	if err != nil {
		fmt.Println(err)
		return
	}

	outputValue, err := vm.Get("output")
	if err != nil {
		fmt.Println(err)
		return
	}

	outputInterface, _ := outputValue.Export()

	fmt.Println(outputInterface)
}
```

Panic:

> panic: reflect.Set: value of type []interface {} is not assignable to type []int64
> 
> goroutine 1 [running]:
> reflect.Value.assignTo(0x671a80, 0xc0420fd8c0, 0x97, 0x6bedd6, 0xb, 0x671a00, 0x0, 0x0, 0x671a80, 0xc0420fd8c0)
> 	C:/app/Go/src/reflect/value.go:2181 +0x30e
> reflect.Value.Set(0x671a00, 0xc0420efda0, 0x197, 0x671a80, 0xc0420fd8c0, 0x97)
> 	C:/app/Go/src/reflect/value.go:1351 +0xab
> vendor/github.com/robertkrimen/otto.Value.export(0x5, 0x6b4020, 0xc0420f9aa0, 0x0, 0x0)
> 	C:/Users/username/Documents/Eclipse/src/vendor/github.com/robertkrimen/otto/value.go:718 +0xe9f
> vendor/github.com/robertkrimen/otto.Value.Export(0x5, 0x6b4020, 0xc0420f9aa0, 0x0, 0x0, 0x0, 0x0)
> 	C:/Users/username/Documents/Eclipse/src/vendor/github.com/robertkrimen/otto/value.go:648 +0x6e
> main.main()
> 	C:/Users/username/Documents/Eclipse/src/test/main.go:27 +0x344
>

### PR DESCRIPTION
**Pull request by douglaswth**
- I believe this is a more appropriate solution than #377 as it takes
  into account the types of elements in sub arrays, slices, etc.
- This should also fix #279 which was apparently closed although the
  issue still existed.

### CODE REVIEW

**Review by stevenh — CHANGES_REQUESTED** [review]
Can you provide a test which exercises this issues please.

**Comment by douglaswth** [comment]
@stevenh I have added a test case in the style of the existing tests that exercises the mentioned issues.

**Comment by stevenh** [comment]
Thanks @douglaswth.

Do you think https://github.com/robertkrimen/otto/pull/377 is related?

**Comment by douglaswth** [comment]
@stevenh Yes, it fixes the same panic, so merging this should supersede the other PR.

**Comment by stevenh** [comment]
Thanks for the confirmation, looking at #377 its significantly simpler so I would like to understand the benefits from this approach as it’s not clear from just reading the code

**Comment by douglaswth** [comment]
@stevenh For one thing, #377 has the issue brought up in https://github.com/robertkrimen/otto/pull/377#issuecomment-629103960:

```go
	value, _ := vm.Run(`[["aa", "bb"], ["cc", "dd"]]`)
	result, _ := value.Export()
```

Which had previously returned a `result` that is `[][]string` but with the #377 will regress to returning `[]interface {}` instead.

With my change the original intended behavior continues to work and further handles other cases that could cause the panic while setting types when possible.

**Review by stevenh — APPROVED** [review]

**Comment by stevenh** [comment]
Thanks PR @douglaswth, merged 👍

**Pull request merged**
