### PR TITLE
Added function statement to fix AST

### PR DESCRIPTION
**Pull request by wolfgarnet**
When traversing the AST, it is quite annoying function statements are replaced with EmptyStatements. This pull request adds a FunctionStatement in order to fix this.

### CODE REVIEW

**Comment by darkliquid** [comment]
The change itself looks fine to me, but I'm not familiar enough with the AST code and how/where it's used to know if changing this behaviour would be harmful.

A tentative :+1: from me

**Comment by wolfgarnet** [comment]
Is there anything I can do to get this merged?

**Comment by deoxxa** [comment]
I know this is a super late request, but would you be able to put together a test for this? Happy to merge once that's done.

**Comment by stevenh** [comment]
any update on this @wolfgarnet ?

**Comment by stevenh** [comment]
any update on this @wolfgarnet ?

**Comment by wolfgarnet** [comment]
Hi. I didn't have the time to create a test back then and totally forgot about it. I will see if I can find the time.

**Comment by stevenh** [comment]
Long time no hear so just poking @wolfgarnet

**Comment by wolfgarnet** [comment]
Sorry for the late reply, @stevenh. I have had some time to look at it now, and I must admit, it's been quite awhile since I last looked at it.
There are some things that confuses me, mostly because I can't remember the chronology in it and why decisions were made. I looked through the statement.go file for function statement functionality, and found that it was already there. By a later pull request by me: https://github.com/robertkrimen/otto/pull/164 
I don't know if this pull request is still relevant, but it looks a bit dated compared to what's already there.

**Comment by stevenh** [comment]
Thanks for the confirmation @wolfgarnet I will close this for now. If it does become relevant please feel free to reopen.

**Pull request closed without merging**
