### PR TITLE
Add methods for handle timeouts

### LINKED ISSUE #278: Add possibility to set timeout
It would be great to have a possibility to set a timeout to avoid workaround like this https://github.com/robertkrimen/otto#halting-problem

### PR DESCRIPTION
**Pull request by seregayoga**
I added a few new methods for avoiding workaround described in this section https://github.com/robertkrimen/otto#halting-problem
Fixes #278

### CODE REVIEW

**Comment by seregayoga** [comment]
@deoxxa what do you think about this?

**Comment by deoxxa** [comment]
This actually looks perfectly reasonable. I can't really see anything wrong with it, and I'm sure it fits perfectly for this specific use case, but I'm also not *totally* convinced that it needs to be a top-level, core API function.

I'm thinking it might be better to integrate `context.Context` support instead, since that's really emerging as *the* way to do deadlines and timeouts. That is a larger job though and might not happen anytime soon - it depends on someone putting in the work, and I know that I personally don't have the time spare right now. If/when this happens, I wouldn't want to have two (maybe incompatible or conflicting) ways to do timeouts.

What say ye, @stevenh? Any opinions?

**Comment by stevenh** [comment]
Yer context would be good, do we really think it would be that much more
work?

**Comment by deoxxa** [comment]
I'm actually not sure - I'm just assuming there could be tricky stuff. It might be as easy as wiring up a handler between `context.Done` and the existing interrupt channel though. I won't have time to investigate it for at least the next couple of weeks though.

**Comment by seregayoga** [comment]
@deoxxa what signature would you like to see? In method Run, for example.

**Review by stevenh — CHANGES_REQUESTED** [review]
This would be better done with context.Context as then we get timeout and cancellation.

**Comment by stevenh** [comment]
Closing due to age with no feedback

**Pull request closed without merging**
