### PR TITLE
Source maps

### PR DESCRIPTION
**Pull request by deoxxa**
This is pretty rough at the moment, but I plan to clean it up and figure out some tests for it.

### CODE REVIEW

**Comment by stevenh** [comment]
Seems you have quite a few unrelated fixes in here?

Also really need to get some tests in for the new stuff.

**Comment by deoxxa** [comment]
The other commits are the content of #115 - without them, the source maps are basically useless as there's no line/column information on a lot of exceptions. I know it needs tests, and they'll come eventually... Luckily I don't think anyone's in a hurry to merge this quite yet!

**Comment by deoxxa** [comment]
This is rebased on master now, and significantly less noisy as a result. I still need to put together tests and such, and I've uncovered a couple of bugs in this particular sourcemap library, so we might have to fork/adopt it.

**Comment by deoxxa** [comment]
I finally ended up getting this tested etc. Now that I look at it again though, I'm not a huge fan of all the `WithSourceMap` functions. Anyone got any ideas to make this less ugly? Preferably without breaking any of the existing API.

**Comment by deoxxa** [comment]
Okay, everything is squashed down and the API is much nicer now. This is pretty much ready to go.

**Comment by deoxxa** [comment]
I'd really like to get this into master soon. Everything appears to work okay, and it doesn't break any of the existing API or tests. If nobody comes forward to tell me this is broken in the next few days, I'm going to merge it into master.

**Pull request merged**
