### PR TITLE
feat:add math function

### PR DESCRIPTION
**Pull request by noobHuKai**
add some math function
- Math.acosh
- Math.asinh
- Math.atanh
- Math.cbrt
- Math.cosh
- Math.expm1
- Math.log10
- Math.log1p
- Math.log2
- Math.sinh
- Math.tanh
- Math.trunc

### CODE REVIEW

**Comment by noobHuKai** [comment]
Don't from Edition 5.1, but from [Edition 6.0](https://262.ecma-international.org/6.0/#sec-function-properties-of-the-math-object)
These math function are common

**Comment by Asday** [comment]
Common as you want:

> * Otto targets ES5. ES6 features (eg: Typed Arrays) are not supported.

-- https://github.com/robertkrimen/otto#caveat-emptor

**Comment by stevenh** [comment]
Lets try an move that forward :)

**Comment by stevenh** [comment]
@noobHuKai as you can see from [failure](https://github.com/robertkrimen/otto/actions/runs/3894272524/jobs/6666156842) `inline.go` is auto generated by [tools/gen-jscore](https://github.com/robertkrimen/otto/tree/master/tools/gen-jscore) so you will need update to its [configuration](https://github.com/robertkrimen/otto/blob/master/tools/gen-jscore/.gen-jscore.yaml) to ensure that's compatible.

**Comment by stevenh** [comment]
FYI I just merged a change which added a notification header to generated files, so it's harder for people to make this mistake in the future.

**Comment by noobHuKai** [comment]
I'm sorry,I'm not familiar with configuration，Thank you for the tip ! ! !

**Comment by stevenh** [comment]
> I'm sorry, I'm not familiar with configuration, Thank you for the tip ! ! !

It's new so no need to be sorry :)

**Review by stevenh — CHANGES_REQUESTED** [review]
Looks good just some formatting issues with the test file, see: https://github.com/robertkrimen/otto/actions/runs/3916742117/jobs/6723701631

**Pull request merged**
