### PR TITLE
Added FPSFunction

### PR DESCRIPTION
**Pull request by Dorbmon**
Maybe it's not very useful.

### CODE REVIEW

**Comment by deoxxa** [comment]
What does this even _do_?

**Comment by Dorbmon** [comment]
I need this to listen the change of variables.

**Review by stevenh — CHANGES_REQUESTED** [review]
Repository address has been changed in the this PR so can't see the wood for the trees :(

Debugging left in (commented out)

Will look to re-review once the above has been corrected.

**Comment by stevenh** [comment]
Closing due to age with no feedback

**Pull request closed without merging**
