### PR TITLE
fix Go map iteration when looping over non-string keys

### PR DESCRIPTION
**Pull request by bontibon**
Fix for issue #96

### CODE REVIEW

**Comment by stevenh** [comment]
Could you add a test for this too please?

**Comment by bontibon** [comment]
@stevenh Added some tests. Hopefully they are sufficient.

**Comment by stevenh** [comment]
Confirmed the tests fail without the fix and pass with it, good work :+1:

**Comment by bontibon** [comment]
Hey, @robertkrimen. Would it be possible to get this merged in soon?  Thanks.

**Comment by robertkrimen** [comment]
Yeah, looks pretty good.

**Comment by robertkrimen** [comment]
This is fixed in d1b4d8ef0e0e4b088c8328c95ca63ab9ebd8fc9d

**Pull request closed without merging**
