### PR TITLE
Some minor corrections

### PR DESCRIPTION
**Pull request by wolfgarnet**
Hi.

This patch primarily corrects some erroneous idx's in some of the node types. In some cases their values were invalid and caused my program to fail.
It also fixes the parsing of regular expression modifiers when they are delimited by a new line(to the next expression).
I have also made the precedence() from token/token.go global, because I use it in my project.
Finally, I have introduced Position() for File, in order to determine the position of an occurrence in a program.

Please let me know if you want me to split the pull request into smaller items.

### CODE REVIEW

**Comment by stevenh** [comment]
@wolfgarnet could you resolve the conflicts?

**Comment by wolfgarnet** [comment]
I will try to find some time to do it.

**Comment by stevenh** [comment]
I know its been some time but just checking if you could find some time to update this @wolfgarnet ?

**Comment by stevenh** [comment]
Closing due to age with no feedback

**Pull request closed without merging**
