### PR TITLE
make call stacks aware of native functions

### PR DESCRIPTION
**Pull request by deoxxa**
* add stackFramesToPop argument to error factories
* put native functions in their own stack frames
* add tests for native stack frames

### CODE REVIEW

**Comment by stevenh** [comment]
Could you update this to fix the conflicts please @deoxxa ?

**Comment by deoxxa** [comment]
Done!

**Comment by darkliquid** [comment]
I *think* this will cause breakages due to the changes I introduced with the Context method. Might need to rebase again to be sure.

**Comment by deoxxa** [comment]
Got a whole bunch more tests. Pretty sure this is working as intended now.

**Comment by deoxxa** [comment]
Okay - I want to get this into master in the next few days. All of the current tests pass, and this patch introduces a handful of new tests, but I'd still like to make sure anyone who cares has a chance to say "no, wait!"

If nobody comes forward over the next few days, I'm going to merge this in.

**Pull request merged**
