### PR TITLE
Simple limitation of evaluation speed.

### PR DESCRIPTION
**Pull request by zond**
A `Limits` struct in the `Otto` struct contains `Burst` and `PerSecond` fields used by `evaluate.go` (if `PerSecond` > 0) to limit the speed with which the runtime can evaluate nodes.

### CODE REVIEW

**Comment by stevenh** [comment]
Seems reasonable any interest in updating it to fix the conflicts @zond ?

**Comment by zond** [comment]
No, I don't work on this any more :/

**Comment by stevenh** [comment]
Closing based on feedback

**Comment by primalmotion** [comment]
Hi, there is still no way to limit cpu usage or am I missing something?

**Comment by slimsag** [comment]
@primalmotion Still not possible AFAIK.

**Comment by slimsag** [comment]
See https://github.com/robertkrimen/otto/issues/54

**Pull request closed without merging**
