### PR TITLE
upgrade underscore

### PR DESCRIPTION
**Pull request by emicklei**

### CODE REVIEW

**Comment by deoxxa** [comment]
It'd be nice to regenerate the `underscore_*_test.go` files as well, and make sure they pass.

**Comment by emicklei** [comment]
The current ones do pass. I wasn't aware that those were generated too. I will try to do so. Thanks.

**Comment by emicklei** [comment]
@deoxxa can you explain how these files are generated ?  (they don't look generated to me)

**Comment by deoxxa** [comment]
@emicklei I believe they're built with the [underscore/testify](https://github.com/robertkrimen/otto/blob/master/underscore/testify) script. I haven't looked to closely at it though, I'm afraid!

**Comment by stevenh** [comment]
Any update on this @emicklei ?

**Comment by emicklei** [comment]
anybody still interested in this?

**Comment by mauriciombb** [comment]
Saw that this PR was closed 5 days ago... was searching now how to upgrade to underscore.js included in the otto's vms. Is this in the roadmap somehow?

**Pull request closed without merging**
