### PR TITLE
Commentmapv2

### PR DESCRIPTION
**Pull request by wolfgarnet**
I have updated my implementation of the comment parsing. A more intuitive way, a bit less intrusive.
It supports some special cases, that the old one didn't. Specifically, comments at line breaks.
It is also more precise regarding the positions of the comments.
I have also added a FunctionStatement to replace the EmptyStatement when parsing functions.

### CODE REVIEW

**Comment by wolfgarnet** [comment]
Hi!
This pull request provides some significant improvements to comment parsing. Please take a look at it.

**Comment by deoxxa** [comment]
Sorry! I'm sure nobody is ignoring it on purpose. I've got a very busy life at the moment, but as soon as I have some spare time I'll take a look at this properly.

**Comment by darkliquid** [comment]
This looks like a really nice refactor of your previous work, nice job! It all looks good to me, tests pass, didn't spot any issues with formatting.

:+1:

**Comment by wolfgarnet** [comment]
I can relate to that, deoxxa. Thank you.

Thanks, darkliquid!

**Comment by deoxxa** [comment]
I've given this a bit of a run through, and everything seems to work okay. Made sure all the tests still pass on current master. Merge time!

**Comment by wolfgarnet** [comment]
Thank you!

**Pull request merged**
