### PR TITLE
Export NewParser and Parser.Scan

### PR DESCRIPTION
**Pull request by amasad**
I want to use Otto's lexer. This just exports the constructor and the Scan method. Thanks

### CODE REVIEW

**Comment by deoxxa** [comment]
This looks okay, but I'd like to avoid exposing things that involve unexported types (i.e. `_parser`).

Could you make a `Parser` interface with a `Scan` member and return that instead? And could you do that from a `NewParser` function that wraps the current `newParser` function instead of renaming it?

**Comment by amasad** [comment]
OK

**Comment by amasad** [comment]
done

**Comment by deoxxa** [comment]
Perfect - thanks!

**Comment by amasad** [comment]
awesome, thanks for the quick turnaround!

**Pull request merged**
