### PR TITLE
add a way to trigger something with `debugger`

### PR DESCRIPTION
**Pull request by deoxxa**

### CODE REVIEW

**Comment by darkliquid** [comment]
Is there more that can be done to aid debugging here? At the moment this doesn't seem like a huge step beyond just manually defining a 'debugger' function in the global scope yourself. Perhaps the func registered could be passed some useful info as a parameter from inside the otto runtime which isn't normally available, to aid in more complex debugging scenarios?

**Comment by deoxxa** [comment]
@darkliquid yep, this is designed to work in tandem with #143. I've got a little REPL thing going on in a project that uses otto, where when the program hits a `debugger` statement it pops open a REPL on the terminal where the program is running.

The reason this doesn't do anything in particular is that we can't know where otto is being used. It might be in an HTTP server, or a command line program, or even something without a terminal. I think it's up to the consuming program what should happen when the interpreter encounters `debugger`.

I want to add a couple of arguments to the function signature before this goes in - I'm thinking `func(vm *otto.Otto, callerLocation *somethingThatDoesNotExistYet)`, where the second argument has some information about where the `debugger` statement actually is.

**Comment by darkliquid** [comment]
Nice. 

Re: your second paragraph, I completely agree. This should definitely be an optional callback that is user-defined, not some arbitrary behaviour we enforce on users which might not be appropriate to their projects.

Your last paragraph pretty much sums up what I was thinking of. It'd be nice to have some kind of structure for that second param that exposed the stack info, accessible variables, line numbers/files, etc - but that's likely a lot more accounting work which probably belongs in another commit for now.

:+1:

**Comment by deoxxa** [comment]
@darkliquid the first part of this is sorted now. I'm not sure what the API for the second bit should look like, nor am I sure it should be available only for a `debugger` hook. Perhaps this kind of information should be available from the VM (on request) all the time?

**Comment by darkliquid** [comment]
That's a good point. While it would make sense for the debugger hook to provide it, you're right in that it probably has a wider utility outside of that. Time to open another issue I think for some RFCs on the matter, see if we can't come up with something that will be useful.

**Comment by deoxxa** [comment]
Sounds like a good idea.

**Comment by darkliquid** [comment]
Also, change looks good now :+1:

**Pull request merged**
